spring:
  application:
    name: farmer
  datasource:
    url: jdbc:postgresql://localhost:5432/farmer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

twilio:
  phoneNumber: ${TWILIO_PHONE_NUMBER}
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}

jwt:
  secret: ${JWT_SECRET}
  access-token-ms: 3600000   # 1 hour
  refresh-token-ms: 604800000  # 7 days
  cleanup:
    cron: "0 0 0 * * ?"

otp:
  expiration:
    minutes: 5

server:
  port: 8080

logging:
  level:
    com.yourpackage: DEBUG
    org.springframework.security: DEBUG

sms:
  mock:
    enabled: true
