spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}

twilio:
  phoneNumber: ${TWILIO_PHONE_NUMBER}
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}

jwt:
  secret: ${JWT_SECRET}
  access-token-ms: ${JWT_ACCESS_TOKEN_MS}
  refresh-token-ms: ${JWT_REFRESH_TOKEN_MS}
  cleanup:
    cron: "0 0 0 * * ?"

otp:
  expiration:
    minutes: ${OTP_EXPIRATION_MINUTES}

server:
  port: ${SERVER_PORT}

logging:
  level:
    com.yourpackage: DEBUG
    org.springframework.security: DEBUG
