# Application Configuration
spring:
  application:
    name: ai-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: agriculture-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            use:
              type:
                headers: false
            value:
              default:
                type: com.ubaid.ai_service.model.SoilData
      auto-offset-reset: earliest
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Gemini AI Configuration
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent

# Logging Configuration
logging:
  level:
    com.ubaid.ai_service: INFO
    org.apache.kafka: WARN
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.kafka: INFO

server:
  port: ${SERVER_PORT:8082}
